Allow testnet magic to be specified on the command line
input-output-hk/cardano-node pull request #2028
Opened 2020-10-28 06:06 UTC by newhoggy

2020-10-28 08:14 UTC, mrBliss requested changes

2020-10-28 08:14 UTC, mrBliss commented on cardano-node-chairman/testnet/Testnet/Commands/ByronShelley.hs
> +        <>  value 4
Threads?

2020-10-28 08:14 UTC, mrBliss commented on cardano-node-chairman/testnet/Testnet/Commands/Shelley.hs
> +        <>  value 4
Same

2020-10-28 08:41 UTC, newhoggy commented on cardano-node-chairman/testnet/Testnet/Commands/ByronShelley.hs
> +        <>  value 4
Oops, copy past error 😅

2020-10-28 22:56 UTC, erikd approved these changes

2020-10-28 23:08 UTC, intricate approved these changes

2020-10-29 00:23 UTC, newhoggy commented
bors merge

2020-10-29 03:07 UTC, newhoggy commented
bors merge

2020-10-29 03:45 UTC, merged