Modify tip cardano-cli query to also return the current epoch
input-output-hk/cardano-node pull request #2440
Opened 2021-03-03 10:52 UTC by Jimbo4350

2021-03-04 09:57 UTC, dcoutts requested changes

2021-03-04 09:57 UTC, dcoutts commented on cardano-api/src/Cardano/Api/Block.hs
> +                | ChainPoint !SlotNo !(Hash BlockHeader) (Maybe EpochNo)
Oh, no we cannot change this. A point is fundamental. This is what it is, no more no less.

In the CLI we can pair up a point with an epoch number, but we cannot change the point type.

2021-03-04 14:51 UTC, dcoutts requested changes
I think this will be better to do entirely in the CLI in the short term. I don't think we want to change the `getLocalChainTip`, since it changes it from being a single chain sync query to being two protocols, with a possibility of failure. It doesn't make for a nice API.

In the CLI we can use the existing `getLocalChainTip`, and then use the existing `queryNodeLocalState` with the `QueryEpoch` query. That would not need any API changes.

Now it's true that this is imperfect, since it needs two queries that are not guaranteed to be synchronised (which is the root of the "Maybe" problem in the API in the current version of the patch).

What would be better here, in the medium term, would be to properly make use of the ability of the query to supply no point and implicitly acquire the current point. Then we can use `QueryChainPoint` and `QueryEpoch`. The only thing we're missing to make this perfect is `QueryChainBlockNo`. If we add that query to the consensus, and expose it in the API, then we can do this all as a single query (or rather a single atomic batch of queries).

2021-03-05 12:57 UTC, dcoutts approved these changes
This looks much better.

Two minor comments below.

Lets squash down to one patch again, and clean up the unnecessary changes in whitespace and comments (that are just there as a result of us going back and forth on things).

2021-03-05 12:57 UTC, dcoutts commented on cardano-cli/src/Cardano/CLI/Shelley/Run/Query.hs
> +        output = LBS.concat [pTip, LBS.fromStrict (Text.encodeUtf8 "\n"), epoch]
How about merging these into one json object?
```
output = encodePretty (tip <> toObject mEpoch)
```

One object as output is probably what people want anyway.

2021-03-08 11:48 UTC, Jimbo4350 commented
bors r+

2021-03-08 15:08 UTC, Jimbo4350 commented
bors r+

2021-03-09 10:07 UTC, Jimbo4350 commented
bors r+

2021-03-09 12:04 UTC, olgahryniuk approved these changes

2021-03-09 12:20 UTC, Jimbo4350 commented
bors r+

2021-03-09 12:35 UTC, merged