Remove work around
input-output-hk/cardano-node pull request #2611
Opened 2021-04-15 23:10 UTC by newhoggy

2021-04-15 23:59 UTC, erikd requested changes
Seems fine, but please retittle the commit so its obvious that its the GH actions where a wrokaround was removed.

2021-04-16 04:35 UTC, newhoggy commented
This particular `apt-get` repository was previously causing issues due to flakiness and was previous removed at the beginning of the build.  Github Actions have removed this from the initial repository list, so builds are now failing and the the work around is no longer needed.

2021-04-16 06:02 UTC, Jimbo4350 approved these changes

2021-04-16 06:10 UTC, newhoggy commented
bors merge

2021-04-16 06:44 UTC, merged