If only one of IPv4 / IPv6 is configured, try the other protocol silently
input-output-hk/cardano-node pull request #2773
Opened 2021-06-01 14:28 UTC by weebl2000

Do not fail if it is missing, unlike when both IPv4 and IPv6 are missing.

should fix #2732

2021-06-24 16:14 UTC, weebl2000 commented
@coot I heard you were involved with networking side of things. I was just wondering if this is something that is desirable behavior or not. This is my first PR to cardano-node, I'm not sure if there is some other process I should go through in the development process. If so, please let me know. :)

2021-06-25 06:58 UTC, coot requested changes
This looks good, thanks for your contribution; Just a minor change request.

2021-06-25 07:12 UTC, coot commented
However this removes the ability of using `ipv4` only on a `ipv6` capable host so I am not sure if this change is desirable.  If you want to use `ipv6` you can be explicit about it.

2021-06-25 07:32 UTC, coot commented
After a discussion we decided against this change because it limits the way one can configure a node.  It turns out that there many ipv6 capable hosts which are connected to ipv6 networks that are not connected to the internet.

2021-06-25 07:32 UTC, closed without merging

2021-06-25 07:56 UTC, weebl2000 commented
> After a discussion we decided against this change because it limits the way one can configure a node. It turns out that there many ipv6 capable hosts which are connected to ipv6 networks that are not connected to the internet.

I agree you should be able to configure without IPv6, but currently I feel a lot of operator will not know they are limiting IPv6 operation if they only specify IPv4 host address. Would it be a good addition to do add this behavior if an IPv6 address is specified in the topology file? @coot

2021-06-25 08:11 UTC, weebl2000 commented
> After a discussion we decided against this change because it limits the way one can configure a node. It turns out that there many ipv6 capable hosts which are connected to ipv6 networks that are not connected to the internet.

I think the primary concern would be IPv6 hosts that *are* connected to the internet that do not want to connect to IPv6 cardan nodes.