Update deps 20210723
input-output-hk/cardano-node pull request #2966
Opened 2021-07-26 12:15 UTC by Jimbo4350

2021-07-26 14:50 UTC, dcoutts requested changes

2021-07-26 14:50 UTC, dcoutts commented on cardano-api/src/Cardano/Api.hs
> +    fromAlonzoRdmrPtr,
No, not to be exported from the main API. From the `.Shelley` module at most.

2021-07-26 14:50 UTC, dcoutts commented on cardano-api/src/Cardano/Api.hs
> +    renderScriptWitnessIndex,
Put this next to the export of `ScriptWitnessIndex` itself. It is not a conversion.

2021-07-26 14:50 UTC, dcoutts commented on cardano-api/src/Cardano/Api/Fees.hs
> +  obtainHasField ShelleyBasedEraAlonzo  f = f
Note that we should really deprecate `transactionFee`. It is wrong for Alonzo. It should be replaced by `evaluateTransactionFee`.

2021-07-26 14:50 UTC, dcoutts commented on cardano-api/src/Cardano/Api/Tx.hs
> +                  (strictMaybeToMaybe auxiliaryData)
There's a lot of changes here, both specifically here and in the rest of the module. It's unclear what are the forced changes due to the update and what is reformatting. Could we try to split those up? i.e. keep _just_ the necessary changes, and if we want to do reformatting or other refactoring, have those in separate commits, either before or after the dep update.

2021-07-26 16:02 UTC, dcoutts approved these changes

2021-07-26 22:46 UTC, dcoutts commented
bors merge

2021-07-26 22:58 UTC, dcoutts commented
Hmm, the plutus example CI instance failing the build is really odd. It's as if it is not using the right ledger commit. The final patch is exactly about removing the type applications that are no longer necessary, but those builds are failing as if they are still necessary.

2021-07-27 06:24 UTC, coot approved these changes

2021-07-27 09:17 UTC, Jimbo4350 commented
bors r+

2021-07-27 09:36 UTC, Jimbo4350 commented
bors merge

2021-07-27 10:31 UTC, merged