Remove http server running on a public port.
input-output-hk/cardano-node pull request #3031
Opened 2021-08-05 14:59 UTC by MarcFontaine

A webserver was started by the workbench.
It is unclear why it would be needed.
It could be a possible security risk.

2021-08-05 15:09 UTC, deepfire requested changes
@MarcFontaine, since you remove that instead of disabling by default -- can I ask you to negotiate this change with @mkoura ?

2021-08-05 15:24 UTC, mkoura commented
In QA we don't use that supervisor cluster anymore, so we are not affected by the change.
However I don't see anything wrong with running that http server. The http server serves pools metadata on address:port that each pool announced during pool registration, so it's desirable to keep it there.

2021-09-04 09:27 UTC, MarcFontaine commented
@deepfire The PR has already been prepared and we have a confirmation from Martin that the http server is not used by the QA team any longer.
I suggest that we merge this PR and remove it.

2022-10-27 10:56 UTC, Jimbo4350 commented
Closing this. Please re-open this PR if it is still relevant.

2022-10-27 10:56 UTC, closed without merging