New query stake pools command
input-output-hk/cardano-node pull request #3137
Opened 2021-08-28 09:59 UTC by newhoggy

2021-08-28 10:00 UTC, newhoggy commented
Example output:

```bash
$ CARDANO_NODE_SOCKET_PATH=socket cardano-cli query stake-pools --testnet-magic 1097911063 --cardano-mode
pool1qqyjr9pcrv97gwrueunug829fs5znw6p2wxft3fvqkgu5f4qlrg
pool1qqfnw2fwajdnam7xsqhhrje5cgd8jcltzfrx655rd23eqlxjfef
pool1qquwwu6680fr72y4779r2kpc7mxtch8rp2uhuqcc7v9p6q4f7ph
...
pool1lad5j5kawu60qljfqh02vnazxrahtaaj6cpaz4xeluw5xf023cg
pool1la4ghj4w4f8p4yk4qmx0qvqmzv6592ee9rs0vgla5w6lc2nc8w5
pool1llugtz5r4t6m7xz6es4qu7cszllm5y3uvx3ast5a9jzlv7h3xdu
```

2021-09-03 14:51 UTC, Jimbo4350 requested changes

2021-09-03 14:51 UTC, Jimbo4350 commented on cardano-cli/src/Cardano/CLI/Shelley/Run/Query.hs
> +getSbe :: Monad m => CardanoEraStyle era -> ExceptT ShelleyQueryCmdError m (ShelleyBasedEra era)
Let's not make things polymorphic unless we have to.

2021-09-03 14:51 UTC, Jimbo4350 commented on cardano-cli/src/Cardano/CLI/Shelley/Run/Transaction.hs
> +joinEither :: (x -> z) -> (y -> z) -> Either x (Either y a) -> Either z a
Can we move these to the Helpers module in the cli?

2021-09-03 14:51 UTC, Jimbo4350 commented on cardano-cli/src/Cardano/CLI/Shelley/Run/Transaction.hs
> -      if null txinsc
You have removed txin checks here. Is this is mistake?

2021-09-06 13:09 UTC, closed without merging