Add missing AsType for current Tx eras
input-output-hk/cardano-node pull request #3253
Opened 2021-09-27 15:25 UTC by koslambrou

Motivation: Trying to deserialize a `Tx era` with `deserialiseFromTextEnvelope` requires as parameter of type `AsType`. Currently we only have `AsByronTx` and `AsShelleyTx`. Therefore, this PR extends this to all current eras.

2021-09-27 16:09 UTC, dcoutts requested changes
Thanks. What we should do is deprecate `pattern AsByronTx` and `pattern AsShelleyTx`. They should be deprecated in favour of `AsTx AsByronEra` and `AsTx AsShelleyEra`. And all the other eras follow that pattern, using `AsTx` with the "As" type for the era.

2021-09-27 16:19 UTC, koslambrou commented
@dcoutts Thanks for the comment! I deprecated instead those patterns.

2021-09-28 07:18 UTC, newhoggy approved these changes

2021-09-28 09:44 UTC, dcoutts approved these changes
LGTM! Thanks!

2021-09-28 10:07 UTC, koslambrou commented
bors r+

2021-09-28 12:00 UTC, koslambrou commented
bors merge

2021-09-28 12:03 UTC, Jimbo4350 commented
bors r+

2021-09-28 19:01 UTC, Jimbo4350 commented
bors r+

2021-09-28 19:19 UTC, merged