cardano-node:  factor tracing-independent mini-API as Cardano.Node.Queries
input-output-hk/cardano-node pull request #3378
Opened 2021-11-19 15:40 UTC by deepfire

The current tracing system makes a number of projections of the system state, which are not really tracing-system specific.

We consolidate those as modules under `Cardano.Node.Queries`, so this can be reused by old and new tracing systems:

  - Cardano.Node.Queries.ConvertTxId
  - Cardano.Node.Queries.KES
  - Cardano.Node.Queries.Ledger

2021-11-22 11:54 UTC, newhoggy approved these changes
LGTM

2021-11-22 14:10 UTC, Jimbo4350 requested changes
Rather than creating three separate modules, lets put all of this into one module.

2021-11-22 14:10 UTC, Jimbo4350 commented on cardano-node/src/Cardano/Node/Queries/KES.hs
> +  (
Extra newline here

2021-11-23 14:49 UTC, Jimbo4350 approved these changes
LGTM!

2021-11-23 14:49 UTC, Jimbo4350 commented on cardano-node/cardano-node.cabal
> +                       Cardano.Node.Queries
Thanks :+1:

2021-11-23 20:11 UTC, deepfire commented
bors r+

2021-11-23 23:21 UTC, deepfire commented
bors r+

2021-11-24 03:06 UTC, deepfire commented
bors r+

2021-11-24 14:57 UTC, merged