Replace Text with LedgerStateError structured errors
input-output-hk/cardano-node pull request #3397
Opened 2021-11-29 12:27 UTC by DavidEichmann

2021-11-29 15:26 UTC, Jimbo4350 requested changes
Looking good. A couple comments.

2021-11-29 15:26 UTC, Jimbo4350 commented on cardano-api/src/Cardano/Api/LedgerState.hs
> +  FoldBlocksApplyBlockError err -> "Failed when applying a block: " <> textShow err
What would be better is a `renderLedgerStateError :: LedgerStateError -> Text` function that outputs something similar to the comments you put by the `LedgerStateError` definition.

2021-11-29 15:26 UTC, Jimbo4350 commented on cardano-api/src/Cardano/Api/LedgerState.hs
> +            Nothing -> Left InvalidRollback
Would it be useful for debugging to have additional context in `InvalidRollback`? E.g the `slotNo`?

2021-12-01 15:13 UTC, Jimbo4350 approved these changes
Thanks @DavidEichmann. Just squash the commits and replace `textShow` with `renderLedgerStateError`

2021-12-01 15:13 UTC, Jimbo4350 commented on cardano-api/src/Cardano/Api/LedgerState.hs
> +      SlotNo     -- ^ Oldest known slot number that we can roll back to.
:+1: Nice, I think this will be useful information.

2021-12-01 15:13 UTC, Jimbo4350 commented on cardano-api/src/Cardano/Api/LedgerState.hs
> +renderLedgerStateError :: LedgerStateError -> Text
:+1:

2021-12-08 11:18 UTC, DavidEichmann commented
bors merge

2021-12-08 11:39 UTC, merged