Update transaction sign command to allow for incremental signing
input-output-hk/cardano-node pull request #3549
Opened 2022-01-28 15:47 UTC by Jimbo4350

Resolves: #3545

2022-02-09 10:17 UTC, newhoggy approved these changes

2022-02-10 14:04 UTC, Jimbo4350 commented
bors r+

2022-02-10 19:22 UTC, Jimbo4350 commented
bors r+

2022-02-11 09:57 UTC, Jimbo4350 commented
bors r+

2022-02-11 15:23 UTC, cblp requested changes

2022-02-11 15:23 UTC, cblp commented on cardano-cli/src/Cardano/CLI/Types.hs
> +data TxBodyOrTxFile
InputTxFile already exists

2022-02-11 20:42 UTC, Jimbo4350 commented
bors r+

2022-02-11 22:25 UTC, Jimbo4350 commented
bors r-

2022-02-15 12:44 UTC, Jimbo4350 commented
bors r+

2022-02-15 14:30 UTC, cblp approved these changes

2022-02-15 18:58 UTC, Jimbo4350 commented
bors r+

2022-02-15 19:24 UTC, merged