Modify tracing defaults to fit the POM model
input-output-hk/cardano-node pull request #3570
Opened 2022-02-04 16:59 UTC by Jimbo4350

2022-02-04 21:14 UTC, coot requested changes
Very nice, I just would like to request to keep some of the traces on by default (as it was introduced in the commit: 05255365d).

2022-02-04 21:14 UTC, coot commented on cardano-node/src/Cardano/Tracing/Config.hs
> +      (PartialTracingOff, PartialTracingOff) -> PartialTracingOff
This case is redundant, although I see the point of keeping it.

2022-02-04 21:14 UTC, coot commented on cardano-node/src/Cardano/Tracing/Config.hs
> +        PartialTracingOnLegacy pts
This can be simplified to
```suggestion
      (_ , tracing) -> tracing
```

2022-02-04 21:14 UTC, coot commented on cardano-node/src/Cardano/Tracing/Config.hs
> +    , pTraceConnectionManager = pure $ OnOff False
```suggestion
    , pTraceConnectionManager = pure $ OnOff True
```

2022-02-04 21:14 UTC, coot commented on cardano-node/src/Cardano/Tracing/Config.hs
> +    , pTraceInboundGovernor = pure $ OnOff False
```suggestion
    , pTraceInboundGovernor = pure $ OnOff True
```

2022-02-04 21:14 UTC, coot commented on cardano-node/src/Cardano/Tracing/Config.hs
> +    , pTracePeerSelection = pure $ OnOff False
```suggestion
    , pTracePeerSelection = pure $ OnOff True
```

2022-02-04 21:14 UTC, coot commented on cardano-node/src/Cardano/Tracing/Config.hs
> +    , pTracePeerSelectionActions = pure $ OnOff False
```suggestion
    , pTracePeerSelectionActions = pure $ OnOff True
```

2022-02-07 16:06 UTC, coot approved these changes
LGTM

2022-02-07 16:31 UTC, deepfire approved these changes
The new tracing system is not intended to be toggle-able on a per-tracer basis.

So while it's a cleanup, it's a little misleading -- the config tracer toggles will have no effect, at least for now.

In future, we might still resort to it, but that's not the current intention.

2022-02-08 19:39 UTC, erikd approved these changes
Probably want to squash this down.

2022-02-09 10:05 UTC, newhoggy commented
All the tests appear to fail in the same way:

```
  ✗ prop_sanityCheck_POM failed at test/Test/Cardano/Node/POM.hs:42:19
    after 1 test.
  
       ┏━━ test/Test/Cardano/Node/POM.hs ━━━
    34 ┃ prop_sanityCheck_POM :: Property
    35 ┃ prop_sanityCheck_POM =
    36 ┃    withTests 1 . Hedgehog.property $ do
    37 ┃     let combinedPartials = defaultPartialNodeConfiguration
    38 ┃                              <> testPartialYamlConfig
    39 ┃                              <> testPartialCliConfig
    40 ┃         nc = makeNodeConfiguration combinedPartials
    41 ┃     case nc of
    42 ┃       Left err -> failWith Nothing $ "Partial Options Monoid sanity check failure: " <> err
       ┃       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       ┃       │ Partial Options Monoid sanity check failure: Default value not specified for TracingVerbosity
    43 ┃       Right config -> config === expectedConfig
  
```

2022-02-09 13:40 UTC, Jimbo4350 commented
bors r+

2022-02-09 14:53 UTC, Jimbo4350 commented
bors merge

2022-02-09 15:13 UTC, merged