cardano-cli: Add friedly printing of transactions (envelopes) with signatures
input-output-hk/cardano-node pull request #3617
Opened 2022-02-17 19:01 UTC by cblp

2022-02-18 11:42 UTC, Jimbo4350 requested changes

2022-02-18 11:42 UTC, Jimbo4350 commented on cardano-cli/src/Cardano/CLI/Run/Friendly.hs
> +-- import           Cardano.Ledger.Shelley.TxBody (WitVKey (..))
Left over comment?

2022-02-18 11:42 UTC, Jimbo4350 commented on cardano-cli/src/Cardano/CLI/Run/Friendly.hs
> +  ("witnesses" .= map friendlyKeyWitness witnesses) : friendlyTxBody era body
We need to also render required signers.

2022-02-18 14:13 UTC, Jimbo4350 reviewed
Almost there

2022-02-18 14:13 UTC, Jimbo4350 commented on cardano-cli/src/Cardano/CLI/Run/Friendly.hs
> +    , "witnesses-extra (payment key hashes needed for scripts)" .=
this should be "required-signers"

2022-02-18 15:05 UTC, cblp commented on cardano-cli/src/Cardano/CLI/Run/Friendly.hs
> +      ByronKeyWitness txInWitness -> ["input witness" .= textShow txInWitness]
done

2022-03-02 15:02 UTC, cblp commented
bors merge

2022-03-02 15:22 UTC, merged