Update dependencies and pins.
input-output-hk/cardano-node pull request #3700
Opened 2022-03-11 12:12 UTC by nc6

- The `cardano-base`, `cardano-ledger`, `plutus` and `ouroboros-network`
  dependencies have been updated to recent versions.
- Since the downstream libraries have been updated to more recent
  index-state and hackage revisions, we synchronise this here.
- As a consequence of this update, we switch to a newer version of
  `aeson`, necessitating updates in `ekg-json` and `hedgehog-extras`.
- We switch to ghc8107, to be in sync with other packages.

2022-03-16 16:14 UTC, Jimbo4350 requested changes

2022-03-16 16:14 UTC, Jimbo4350 commented on cardano-api/src/Cardano/Api/TxMetadata.hs
> +import qualified Data.Aeson.KeyMap as KeyMap
These imports should be with `Data.Aeson` above

2022-03-16 16:14 UTC, Jimbo4350 commented on cardano-api/src/Cardano/Api/Value.hs
> +import qualified Data.Aeson.KeyMap as KeyMap
This import should be with `Data.Aeson` above

2022-03-16 16:14 UTC, Jimbo4350 commented on cardano-cli/src/Cardano/CLI/Run/Friendly.hs
> +import qualified Data.Aeson.Key as Aeson
This import should be  with `Data.Aeson` above

2022-03-16 16:14 UTC, Jimbo4350 commented on cardano-cli/src/Cardano/CLI/Shelley/Output.hs
> +import qualified Data.Aeson.Key as Aeson
This import should be with `Data.Aeson` above

2022-03-16 16:14 UTC, Jimbo4350 commented on cardano-node/cardano-node.cabal
> -                      , unordered-containers
:tada:

2022-03-30 12:31 UTC, Jimbo4350 approved these changes

2022-03-30 18:40 UTC, deepfire approved these changes

2022-03-30 19:38 UTC, JaredCorduan approved these changes
@nc6 thank you for this huge effort!

2022-04-01 07:26 UTC, coot approved these changes
LGTM

2022-04-01 07:30 UTC, nc6 commented
bors merge

2022-04-01 08:02 UTC, merged