Dep bump 2022-04-22
input-output-hk/cardano-node pull request #3817
Opened 2022-04-22 15:42 UTC by Jimbo4350

2022-04-26 07:12 UTC, coot approved these changes
LGTM

2022-04-26 09:15 UTC, amesgen requested changes
I ported the tracing logic for the pipelining events (from https://github.com/input-output-hk/cardano-node/pull/3764) in [this patch](https://gist.github.com/amesgen/cecfbc3a558aacae7ec672def880cc7d). This also includes a change to `doelide`; there will be a follow-up PR at some point (but this is not blocking this PR).

Apart from that, LGTM.

2022-04-26 11:31 UTC, Jimbo4350 commented
> there will be a follow-up PR at some point (but this is not blocking this PR).

@amesgen  if this is not blocking the PR, why are you requesting changes?

2022-04-26 11:35 UTC, amesgen commented
I was referring to the follow-up PR, it will refine the `doelide` logic. The patch I linked to should be applied in this PR.

2022-04-26 15:53 UTC, amesgen approved these changes

2022-05-02 09:52 UTC, jbgi commented
Fix for the cardano-node-edge test is at https://github.com/input-output-hk/ouroboros-network/pull/3729

2022-05-03 10:25 UTC, newhoggy approved these changes

2022-05-03 11:36 UTC, newhoggy commented
bors merge

2022-05-03 12:50 UTC, newhoggy commented
I backed out the last two commits as per @Jimbo4350's instruction and will try merging again to see if that helped.

2022-05-03 13:11 UTC, Jimbo4350 commented
@newhoggy I think https://github.com/input-output-hk/ouroboros-network/pull/3729 has to be merged first. My commits don't fix the problem.

2022-05-03 14:59 UTC, MarcFontaine approved these changes

2022-05-03 22:02 UTC, newhoggy commented on cardano-api/src/Cardano/Api/Block.hs
> +      getShelleyBlockTxs era shelleyBlockRaw -- HERE
```
src/Cardano/Api/Block.hs:173:30: error:
    • Could not deduce: Ledger.Crypto (ShelleyLedgerEra era)
                        ~ Consensus.StandardCrypto
      from the context: Consensus.ShelleyBasedEra (ShelleyLedgerEra era)
        bound by a type expected by the context:
                   Consensus.ShelleyBasedEra (ShelleyLedgerEra era) => [Tx era]
        at src/Cardano/Api/Block.hs:173:7-44
      Expected type: Ledger.Block
                       (TPraos.BHeader (Ledger.Crypto (ShelleyLedgerEra era)))
                       (ShelleyLedgerEra era)
        Actual type: Ledger.Block
                       (Ouroboros.Consensus.Shelley.Protocol.Abstract.ShelleyProtocolHeader
                          (Consensus.TPraos Consensus.StandardCrypto))
                       (ShelleyLedgerEra era)
    • In the second argument of 'getShelleyBlockTxs', namely
        'shelleyBlockRaw'
      In the second argument of '($)', namely
        'getShelleyBlockTxs era shelleyBlockRaw'
      In the expression:
        obtainConsensusShelleyBasedEra era
          $ getShelleyBlockTxs era shelleyBlockRaw
    • Relevant bindings include
        shelleyBlockRaw :: Ledger.Block
                             (Ouroboros.Consensus.Shelley.Protocol.Abstract.ShelleyProtocolHeader
                                (Consensus.TPraos Consensus.StandardCrypto))
                             (ShelleyLedgerEra era)
          (bound at src/Cardano/Api/Block.hs:171:54)
        era :: ShelleyBasedEra era
          (bound at src/Cardano/Api/Block.hs:171:27)
        getBlockTxs :: Block era -> [Tx era]
          (bound at src/Cardano/Api/Block.hs:162:1)
    |
173 |       getShelleyBlockTxs era shelleyBlockRaw
    |                              ^^^^^^^^^^^^^^^
```

2022-05-03 22:03 UTC, newhoggy commented on cardano-api/src/Cardano/Api/Block.hs
> +              = Consensus.ShelleyHash (TPraos.HashHeader (Cardano.Crypto.Hash.Class.UnsafeHash hashSBS)), -- HERE
```
src/Cardano/Api/Block.hs:173:30: error:
    • Could not deduce: Ledger.Crypto (ShelleyLedgerEra era)
                        ~ Consensus.StandardCrypto
      from the context: Consensus.ShelleyBasedEra (ShelleyLedgerEra era)
        bound by a type expected by the context:
                   Consensus.ShelleyBasedEra (ShelleyLedgerEra era) => [Tx era]
        at src/Cardano/Api/Block.hs:173:7-44
      Expected type: Ledger.Block
                       (TPraos.BHeader (Ledger.Crypto (ShelleyLedgerEra era)))
                       (ShelleyLedgerEra era)
        Actual type: Ledger.Block
                       (Ouroboros.Consensus.Shelley.Protocol.Abstract.ShelleyProtocolHeader
                          (Consensus.TPraos Consensus.StandardCrypto))
                       (ShelleyLedgerEra era)
    • In the second argument of 'getShelleyBlockTxs', namely
        'shelleyBlockRaw'
      In the second argument of '($)', namely
        'getShelleyBlockTxs era shelleyBlockRaw'
      In the expression:
        obtainConsensusShelleyBasedEra era
          $ getShelleyBlockTxs era shelleyBlockRaw
    • Relevant bindings include
        shelleyBlockRaw :: Ledger.Block
                             (Ouroboros.Consensus.Shelley.Protocol.Abstract.ShelleyProtocolHeader
                                (Consensus.TPraos Consensus.StandardCrypto))
                             (ShelleyLedgerEra era)
          (bound at src/Cardano/Api/Block.hs:171:54)
        era :: ShelleyBasedEra era
          (bound at src/Cardano/Api/Block.hs:171:27)
        getBlockTxs :: Block era -> [Tx era]
          (bound at src/Cardano/Api/Block.hs:162:1)
    |
173 |       getShelleyBlockTxs era shelleyBlockRaw
    |                              ^^^^^^^^^^^^^^^

src/Cardano/Api/Block.hs:307:40: error:
    • Couldn't match type 'TPraos.HashHeader crypto0'
                     with 'Cardano.Crypto.Hash.Class.Hash
                             (Cardano.Ledger.Crypto.HASH Consensus.StandardCrypto)
                             Cardano.Ledger.Hashes.EraIndependentBlockHeader'
      Expected type: Cardano.Ledger.Keys.Hash
                       Consensus.StandardCrypto
                       Cardano.Ledger.Hashes.EraIndependentBlockHeader
        Actual type: TPraos.HashHeader crypto0
    • In the pattern:
        TPraos.HashHeader (Cardano.Crypto.Hash.Class.UnsafeHash hashSBS)
      In the pattern:
        Consensus.ShelleyHash (TPraos.HashHeader (Cardano.Crypto.Hash.Class.UnsafeHash hashSBS))
      In the pattern:
        Consensus.HeaderFields {Consensus.headerFieldHash = Consensus.ShelleyHash (TPraos.HashHeader (Cardano.Crypto.Hash.Class.UnsafeHash hashSBS)),
                                Consensus.headerFieldSlot, Consensus.headerFieldBlockNo}
    |
307 |               = Consensus.ShelleyHash (TPraos.HashHeader (Cardano.Crypto.Hash.Class.UnsafeHash hashSBS)),
    |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

2022-05-05 09:35 UTC, nc6 commented
Closing in favour of #3818

2022-05-05 13:38 UTC, Jimbo4350 commented
It is easier to separate concerns if this is merged prior to #3818

2022-05-05 13:39 UTC, closed without merging