Workbench:  integrate cardano-tracer
input-output-hk/cardano-node pull request #3879
Opened 2022-05-20 02:26 UTC by deepfire

1. `cardano-node-service` -- a NixOS service
2. workbench integration
3. a bunch of `Makefile` targets:
    - `smoke-tracer`
    - `10-tracer`
    - `forge-stress-tracer`
    - `chainsync-early-byron-tracer`
    - `chainsync-early-alonzo-tracer`

2022-05-20 06:30 UTC, denisshevchenko commented on nix/nixos/cardano-tracer-service.nix
> +        };
After RTView will be merged in `master` (https://github.com/input-output-hk/cardano-node/pull/3852), `hasRTView` will be added here.

2022-05-20 06:30 UTC, denisshevchenko approved these changes

2022-05-20 13:42 UTC, denisshevchenko commented
bors r+

2022-05-20 14:03 UTC, Jimbo4350 commented
bors cancel

2022-05-20 14:03 UTC, Jimbo4350 requested changes
I asked in the node channel to not merge anymore PRs until we have a node RC. I expect to have one by the end of the day.

2022-05-20 21:02 UTC, Jimbo4350 approved these changes

2022-05-20 22:27 UTC, deepfire commented
bors r+

2022-05-20 23:46 UTC, disassembler commented
bors r-

2022-05-22 12:13 UTC, deepfire commented
bors r+

2022-05-22 14:38 UTC, deepfire commented
bors r+

2022-05-22 16:55 UTC, deepfire commented
bors merge

2022-05-22 19:43 UTC, deepfire commented
bors r+

2022-05-23 07:42 UTC, denisshevchenko commented
bors r+

2022-05-23 09:40 UTC, merged