Fix kes period info command
input-output-hk/cardano-node pull request #3945
Opened 2022-05-31 11:13 UTC by newhoggy

2022-05-31 12:42 UTC, newhoggy commented
Example output:

```
$ CARDANO_NODE_SOCKET_PATH=example/node-spo1/node.sock cardano-cli query kes-period-info --testnet-magic 42 --op-cert-file example/node-spo1/opcert.cert
✓ Operational certificate's KES period is within the correct KES period interval
✓ The operational certificate counter agrees with the node protocol state counter
{
    "qKesCurrentKesPeriod": 0,
    "qKesEndKesInterval": 60,
    "qKesKesKeyExpiry": null,
    "qKesMaxKESEvolutions": 60,
    "qKesNodeStateOperationalCertificateNumber": 0,
    "qKesOnDiskOperationalCertificateNumber": 0,
    "qKesRemainingSlotsInKesPeriod": 7775071,
    "qKesSlotsPerKesPeriod": 129600,
    "qKesStartKesInterval": 0
}
```

2022-05-31 12:46 UTC, Jimbo4350 requested changes

2022-05-31 13:51 UTC, Jimbo4350 approved these changes
LGTM! We should ask @disassembler to test the command for us to double check its working. We should create an issue somewhere that after the hardfork we will only be able to bump the op cert counter by 1. We will need to update the command to do this check in the Babbage era onwards.

2022-05-31 13:51 UTC, Jimbo4350 commented on cardano-api/src/Cardano/Api/LedgerState.hs
>  -- import qualified Ouroboros.Consensus.Protocol.Praos as Consensus
Can you remove this comment too?

2022-06-04 04:32 UTC, newhoggy commented
bors r+

2022-06-04 05:28 UTC, merged

2022-06-04 06:31 UTC, gitmachtl commented
> Example output `babbage`:
> 
> ```
> $ CARDANO_NODE_SOCKET_PATH=example/node-spo1/node.sock cardano-cli query kes-period-info --testnet-magic 42 --op-cert-file example/node-spo1/opcert.cert
> ✓ Operational certificate's KES period is within the correct KES period interval
> ✓ The operational certificate counter agrees with the node protocol state counter
> {
>     "qKesCurrentKesPeriod": 0,
>     "qKesEndKesInterval": 60,
>     "qKesKesKeyExpiry": null,
>     "qKesMaxKESEvolutions": 60,
>     "qKesNodeStateOperationalCertificateNumber": 0,
>     "qKesOnDiskOperationalCertificateNumber": 0,
>     "qKesRemainingSlotsInKesPeriod": 7775071,
>     "qKesSlotsPerKesPeriod": 129600,
>     "qKesStartKesInterval": 0
> }
> ```

is the plaintext output at the top written to /dev/stderr? otherwise it is a strang mixed format output of plaintext with json, thats not good.

2022-06-04 10:38 UTC, gitmachtl commented
question, will the `qKesNodeStateOperationalCertificateNumber` be set again to `null ` if there was no block produced in the current KesPeriod? or will this value show the latest opcert number used on chain in the past?

2022-06-04 10:57 UTC, gitmachtl commented
this should not greenlit with two checkmarks right? because the new opcert counter 3 is too high when the last one on chain is only 1. but the current output looks like that:

```
✓ Operational certificate's KES period is within the correct KES period interval
✓ The operational certificate counter agrees with the node protocol state counter
{
    "qKesCurrentKesPeriod": 16,
    "qKesEndKesInterval": 136,
    "qKesKesKeyExpiry": null,
    "qKesMaxKESEvolutions": 120,
    "qKesNodeStateOperationalCertificateNumber": 1,
    "qKesOnDiskOperationalCertificateNumber": 3,
    "qKesRemainingSlotsInKesPeriod": 10342913,
    "qKesSlotsPerKesPeriod": 86400,
    "qKesStartKesInterval": 16
}
```