Fix building of Alonzo transaction in Babbage era.
input-output-hk/cardano-node pull request #4166
Opened 2022-07-11 13:10 UTC by newhoggy

This is achieved by auto-converting from Babbage field `protocolParamUTxOCostPerByte` to Alonzo field `protocolParamUTxOCostPerWord`, which is a multiplication by `8`.

Fixes https://github.com/input-output-hk/cardano-node/issues/4164

2022-07-11 13:16 UTC, newhoggy commented on cardano-api/src/Cardano/Api/ProtocolParameters.hs
> +            protocolParamUTxOCostPerWord <|> ((* 8) <$> protocolParamUTxOCostPerByte)
The conversion occurs here.

2022-07-18 13:51 UTC, Jimbo4350 requested changes
One minor adjustment then I will approve

2022-07-22 18:27 UTC, Jimbo4350 approved these changes

2022-07-22 18:29 UTC, Jimbo4350 approved these changes

2022-07-23 02:13 UTC, newhoggy commented
bors r+

2022-07-23 03:23 UTC, merged