Expose module Cardano.Api.Script from cardano-api
input-output-hk/cardano-node pull request #4386
Opened 2022-08-25 08:09 UTC by eyeinsky

I'm writing an indexer for the blockchain from script hash to script https://github.com/input-output-hk/plutus-apps/pull/629 and would like to use the conversion functions from ledger to cardano-api scripts in Cardano.Api.Script, would it be ok to export the module?

2022-08-25 10:15 UTC, koslambrou commented
I would suggest to not expose this hidden module. Instead, add the function you want to export in the `Cardano.Api` module.

2022-08-29 16:11 UTC, Jimbo4350 commented
@eyeinsky `fromShelleyBasedScript` should be exported from `Cardani.Api.Shelley`

2022-08-29 16:11 UTC, Jimbo4350 requested changes
w

2022-08-30 15:19 UTC, eyeinsky commented
@Jimbo4350 done!

2022-10-21 10:32 UTC, eyeinsky commented
@Jimbo4350  Does this PR look good now? [Here](https://github.com/input-output-hk/plutus-apps/blob/55e8b1ff28e6bd3100dc9cea37fdd84e613175f6/marconi/src/Marconi/Index/ScriptTx.hs#L140-L210) is the code we could get rid of and stop maintaining, if this is merged. :)

2022-11-29 18:54 UTC, eyeinsky commented
Closing this in favor of the new PR here https://github.com/input-output-hk/cardano-node/pull/4682

2022-11-29 18:54 UTC, closed without merging