Update ouroboros-network and cardano-ledger dependencies
input-output-hk/cardano-node pull request #4392
Opened 2022-08-26 10:02 UTC by coot

- Reword where to get peers from in understanding-config-files.md
- WIP: Updated ouroboros-network dependency

2022-08-29 13:58 UTC, JurbinM approved these changes

2022-09-27 06:20 UTC, coot commented
`ouroboros-network` was already updated passed input-output-hk/ouroboros-network@9128bfcc0

2022-09-27 14:18 UTC, Jimbo4350 requested changes
Yet again due to a lack of communication we have duplicated work: https://github.com/input-output-hk/cardano-node/pull/4381

2022-10-06 07:51 UTC, Jimbo4350 requested changes
I haven't reviewed the PR put please fix all of the imports to follow the style of the library and undo any style changes

2022-10-06 07:51 UTC, Jimbo4350 commented on cardano-api/src/Cardano/Api/LedgerEvent.hs
> +import Cardano.Ledger.Shelley.Rules.Tick (ShelleyTickEvent(..))
These imports do not follow the style convention

2022-10-06 07:51 UTC, Jimbo4350 commented on cardano-api/src/Cardano/Api/LedgerState.hs
> +import qualified Cardano.Ledger.Shelley.API as ShelleyAPI
These imports do not follow the style convention

2022-10-06 07:51 UTC, Jimbo4350 commented on cardano-api/src/Cardano/Api/Orphans.hs
> +import Cardano.Ledger.Babbage (BabbageTxOut)
These imports do not follow the style convention

2022-10-06 07:51 UTC, Jimbo4350 commented on cardano-api/src/Cardano/Api/Orphans.hs
> +  forall era.
Why have you modified the style here?

2022-10-06 07:51 UTC, Jimbo4350 commented on cardano-api/src/Cardano/Api/Orphans.hs
> -  , ToJSON (Core.PParamsDelta era)
Why have you modified the style here?

2022-10-06 07:51 UTC, Jimbo4350 commented on cardano-api/src/Cardano/Api/Orphans.hs
> -      , "esSnapshots" .= esSnapshots
Why have you modified the style here?

2022-10-06 07:51 UTC, Jimbo4350 commented on cardano-api/src/Cardano/Api/Orphans.hs
> -         , ToJSON (Core.TxOut era)
Why have you modified the style here?

2022-10-06 07:51 UTC, Jimbo4350 commented on cardano-api/src/Cardano/Api/Orphans.hs
> -  , ToJSON (Core.TxOut era)
Why have you modified the style here?

2022-11-03 16:23 UTC, Soupstraw commented
closed in favor of #4608

2022-11-03 16:23 UTC, closed without merging