Allow assembling transactions with no witnesses
input-output-hk/cardano-node pull request #4408
Opened 2022-08-31 09:26 UTC by LudvikGalois

It's possible to write a script which requires no signatures, for
example

```
{
    "scripts": [
        {
            "keyHash": "df243ee05bbe556970c9f8b48088b90549b8c9e41a3380fdede62d16",
            "type": "sig"
        },
        {
            "keyHash": "452c6cc84a5430b4ff720d5692e0ce7f4d37b1f78a3bea99fdbab240",
            "type": "sig"
        },
        {
            "keyHash": "9b925a6b6462e0c7c48fc69a06d1e72d03da30655fd5af40e988140e",
            "type": "sig"
        }
    ],
    "type": "atLeast",
    "required": 0
}
```

As such, it should be supported by the CLI to assemble a transaction
with no witnesses.

Fixes: https://github.com/input-output-hk/cardano-node/issues/3835

2022-08-31 10:54 UTC, newhoggy approved these changes

2022-09-01 15:05 UTC, Jimbo4350 requested changes
@LudvikGalois have you confirmed this works on a local testnet?

2022-09-05 01:26 UTC, LudvikGalois commented
> @LudvikGalois have you confirmed this works on a local testnet?

I've tested that it works in so far as the command in the ticket works and you can assemble the transaction. I didn't check if it was actually a useful thing to do, and it seems like it's not, since it's impossible to submit that transaction. I'm not even sure how to redeem from a SimpleScript - the docs are out of date.

2022-09-13 06:37 UTC, LudvikGalois commented
> @LudvikGalois have you confirmed this works on a local testnet?

I have now confirmed that this allows spending of transactions from script addresses containing a script that requires no signatures.

2022-09-27 14:57 UTC, Jimbo4350 approved these changes
LGTM, QA approval needed

2023-01-05 19:09 UTC, merged