Fix 4493 bug
input-output-hk/cardano-node pull request #4501
Opened 2022-10-03 09:31 UTC by Jimbo4350

Resolves: #4493

2022-10-03 09:45 UTC, erikd requested changes
I totally applaud "Fix bug 4493" in the commit message, but the commit message really should briefly say what the bug was.

2022-10-03 15:39 UTC, mkoura approved these changes
Verified that it fixes issue #4493

2022-10-04 19:51 UTC, erikd approved these changes

2022-10-05 08:45 UTC, Jimbo4350 commented
bors r+

2022-10-05 10:13 UTC, merged