cardano-cli: simplifiy the consumption of 'InputTxBodyOrTxFile`
input-output-hk/cardano-node pull request #4647
Opened 2022-11-18 16:42 UTC by MarcFontaine

This PR makes is easier to use CLI arguments of type `InputTxBodyOrTxFile`
* Reorder `IncompleteTx`
* Add `TxOrTxBody`
* Add `readInputTxBodyOrTxFile :: InputTxBodyOrTxFile -> IO (Either CddlError (InAnyCardanoEra CompleteOrIncompleteTx)`

2022-11-21 16:37 UTC, MarcFontaine commented
This PR implements:
https://github.com/input-output-hk/cardano-node/issues/4646
and
https://github.com/input-output-hk/cardano-node/issues/4576

2022-11-22 10:47 UTC, newhoggy commented on cardano-cli/src/Cardano/CLI/Shelley/Parsers.hs
> +        <> Opt.help "Use leagay YAML format (default)."
Is `leagay` a typo?

2022-11-22 10:53 UTC, newhoggy commented on cardano-cli/src/Cardano/CLI/Shelley/Run/Read.hs
> +  "TextEnvelopeCddl error: " <> Text.pack (displayError cddlErr)
Suggest avoid multiline string literals and use `<>` instead.

2022-11-22 10:55 UTC, newhoggy commented on cardano-cli/src/Cardano/CLI/Shelley/Run/Transaction.hs
> +  --TODO: in principle we should be able to support Byron era txs too
Can you say what currently happens with Byron era transactions?

2022-11-22 10:58 UTC, newhoggy commented on cardano-cli/src/Cardano/CLI/Shelley/Run/Transaction.hs
> +rescue action except = firstExceptT except $ newExceptT action
We should probably move this to a re-usable location, but not right now.

2022-11-22 11:02 UTC, newhoggy commented on cardano-cli/src/Cardano/CLI/Shelley/Run/Transaction.hs
> +  (InAnyCardanoEra era input) <- readInputTxBodyOrTxFile inputTx `rescue` ShelleyTxCmdCddlError
I'm in favour of dropping the redundant parens in this bind.

2022-11-22 11:02 UTC, newhoggy commented on cardano-cli/src/Cardano/CLI/Shelley/Run/Transaction.hs
> +      -- takes the body of the tx  and converts the tx to a tx-body
Remove double space after `tx`.

2022-11-22 11:04 UTC, newhoggy commented on cardano-cli/src/Cardano/CLI/Shelley/Run/Transaction.hs
> +      -- IncompleteTx (IncompleteCddlFormattedTx tx) -> friendlyTxBS era tx
This is an interesting point.  @Jimbo4350

2022-11-22 13:14 UTC, Jimbo4350 requested changes

2022-11-22 13:14 UTC, Jimbo4350 commented on cardano-cli/src/Cardano/CLI/Shelley/Run/Read.hs
> +data IncompleteTx era
What is the benefit of adding the `era` parameter? This has further complicated the code without any obvious benefit.

2022-11-22 13:15 UTC, Jimbo4350 requested changes
I am highly skeptical of the changes to `data IncompleteTx`. I don't see any obvious benefit for the increase in code complexity.

2022-11-23 14:55 UTC, Jimbo4350 commented
> The old definition was the root-cause for the code-duplication in `Cardano.CLI.Shelley.Run.Transaction`.

Lets hold off on the refactor for now as:
```
data IncompleteTx
  = UnwitnessedCliFormattedTxBody (InAnyCardanoEra TxBody)
  | IncompleteCddlFormattedTx (InAnyCardanoEra Tx)
```
Will be eliminated when we remove the cli format, which I will like to do in the next cli release. Once we do that we can revisit the refactor.

2022-11-28 13:19 UTC, Jimbo4350 requested changes
https://github.com/input-output-hk/cardano-node/pull/4647#issuecomment-1325201697

2023-12-09 23:33 UTC, closed without merging