Move implementation inside `runTransactionCmd` to toplevel definitions.
input-output-hk/cardano-node pull request #4673
Opened 2022-11-28 14:16 UTC by MarcFontaine

2022-11-28 14:17 UTC, MarcFontaine commented
https://github.com/input-output-hk/cardano-node/issues/4672

2022-11-28 14:58 UTC, Jimbo4350 requested changes
LGTM but one comment

2022-11-28 14:58 UTC, Jimbo4350 commented on cardano-cli/src/Cardano/CLI/Shelley/Run/Transaction.hs
> +  => CardanoEra era
LGTM, however lets use `AnyCardanoEra` here and add some haddock annotations to the parameters where it's not obvious what they are e.g `Maybe Word`.  The haddocks don't have to be overly descriptive, short succinct ones will do.

2022-11-28 16:13 UTC, Jimbo4350 approved these changes
LGTM!

2022-11-28 16:22 UTC, MarcFontaine commented
bors r+

2022-11-28 16:56 UTC, merged

2022-12-06 14:15 UTC, MarcFontaine commented
https://github.com/input-output-hk/cardano-node/issues/4672