backport to 1.35: add flake outputs that cicero expects
input-output-hk/cardano-node pull request #4769
Opened 2023-01-11 15:01 UTC by dermetfan

This is a partial backport of 04c1e174d24377cf7108c1abc21ff16af4966668.

2023-01-12 13:30 UTC, newhoggy approved these changes

2023-01-12 13:34 UTC, Jimbo4350 requested changes

2023-01-12 13:34 UTC, Jimbo4350 commented on cardano-testnet/test/Spec/Cli/Babbage/LeadershipSchedule.hs
> +    H.byDeadlineM 5 leadershipScheduleDeadline "leadershipSchedule:current:error" $ do
Please look on `master` and update with the appropriate error message.

2023-01-12 13:35 UTC, Jimbo4350 approved these changes

2023-01-17 13:43 UTC, coot commented
@dermetfan I hope you don't mind that I'll merge it.

2023-01-17 13:44 UTC, merged