Better error message for query utxo without oops 2
input-output-hk/cardano-node pull request #4825
Opened 2023-01-21 21:33 UTC by newhoggy

2023-01-21 21:42 UTC, newhoggy commented on cardano-api/src/Cardano/Api/Convenience/Query.hs
> +      & onLeft (throwE . QueryEraMismatch)
Some queries like `QueryUTxO`, `QueryProtocolParameters` and `QueryStakePools` return their own errors so needs to be handled with an extra `ExceptT` stack.

2023-01-24 18:07 UTC, Jimbo4350 requested changes
One minor change

2023-01-25 08:18 UTC, newhoggy commented on cardano-api/src/Cardano/Api/Convenience/Query.hs
> +    ) & onLeft (throwE . AcqFailure)
Yep.  Fixed!

2023-03-29 15:03 UTC, Jimbo4350 requested changes

2023-03-29 15:03 UTC, Jimbo4350 commented on cardano-api/src/Cardano/Api/Convenience/Query.hs
> +  ( lift $ executeLocalStateQueryExpr localNodeConnInfo Nothing $ runExceptT $ runExceptT $ do
I still think this is a decrease in readability. I'll start a discussion on slack today.

2023-03-31 13:36 UTC, newhoggy commented on cardano-api/src/Cardano/Api/Convenience/Query.hs
> +      stakePools <- ExceptT $ ExceptT $ queryExpr stakePoolsQuery
Error handling.

2023-12-09 23:20 UTC, closed without merging