Add slotsInEpoch and slotsToEpochEnd to query tip command
input-output-hk/cardano-node pull request #4912
Opened 2023-02-23 09:40 UTC by newhoggy

2023-03-01 02:13 UTC, newhoggy commented
bors r+

2023-03-01 02:29 UTC, erikd approved these changes

2023-03-01 04:14 UTC, newhoggy commented
bors r+

2023-03-01 15:41 UTC, Jimbo4350 requested changes
`"slotsInEpoch": 314,` is this describing the current slot in the epoch? It looks like it is. We should change the name so `slotInEpoch` as `slotsInEpoch` sounds like the number of slots per epoch.

2023-03-02 17:27 UTC, Jimbo4350 approved these changes
LGTM!

2023-03-02 17:27 UTC, Jimbo4350 commented on cardano-cli/ChangeLog.md
> +- Add `slotsInEpoch` and `slotsToEpochEnd` to output of `query tip` command ([PR 4912](https://github.com/input-output-hk/cardano-node/pull/4912))
Sp: `slotInEpoch`

2023-03-03 06:21 UTC, merged