Fix merge group cancelling issue
input-output-hk/cardano-node pull request #4957
Opened 2023-03-08 22:51 UTC by newhoggy

See https://github.com/orgs/community/discussions/46757?sort=top#discussioncomment-4980818

2023-03-08 23:36 UTC, erikd approved these changes

2023-03-09 00:18 UTC, angerman commented
@newhoggy please make sure to keep notes about this in the knowledge base doc on merge queues. 

Under "common complications" with an _analysis_ and _solution_. This won't be the last time we encounter this 😅

2023-03-09 00:50 UTC, Jimbo4350 requested changes
Please add comments to the changes otherwise its difficult to discern why we have named the concurrency groups this way.

2023-03-09 00:50 UTC, Jimbo4350 commented on .github/workflows/check-cabal-files.yml
> +  group: ${{ github.workflow }}-${{ github.event.type }}-${{ startsWith(github.ref, 'refs/heads/gh-readonly-queue/') && github.ref || github.event.pull_request.number || github.run_id }}
A comment explaining why we are doing this would be really useful.

2023-03-09 01:55 UTC, angerman commented
The fact that we have to replicate this over so many files is a bit ... dissatisfying, it feels like this is going to easily lead to divergence? Do we need a GHA linter?

2023-03-09 08:59 UTC, angerman commented on .github/workflows/check-cabal-files.yml
>  # Limit concurrent runs of this workflow within a single PR
Alright, here's my stab at trying to explain this
```suggestion
# When pushing branches (and/or updating PRs), we do want to cancel previous
# build runs. We assume they are stale now; and do not want to spend CI time and
# resources on continuing to continue those runs. This is what the concurrency.group
# value lets us express. When using merge queues, we now have to consider
# - runs triggers by commits per pull-request
#    we want to cancel any previous run. So they should all get the same group (per PR)
# - runs refs/heads/gh-readonly-queue/<target branch name> (they should all get their unique git ref, we don't want to cancel any of the ones in the queue)
# - if it's neither, we wall back to the run_id (this is a unique number for each workflow run; it does not change if you "rerun" a job)
```

2023-03-09 08:59 UTC, angerman commented on .github/workflows/check-cabal-files.yml
>  # Limit concurrent runs of this workflow within a single PR
@newhoggy what do you think? Might need to reference from the other files.

2023-03-09 17:18 UTC, Jimbo4350 approved these changes

2023-03-09 23:38 UTC, angerman commented
🙈 the replication everywhere. But let's fix that in a different Pr and get this merged to prevent unnecessary merge queue cancellations.

2023-03-10 00:15 UTC, merged