Use cardano-api from separate repository
input-output-hk/cardano-node pull request #5047
Opened 2023-04-03 08:44 UTC by newhoggy

2023-05-12 14:46 UTC, Jimbo4350 approved these changes

2023-05-15 06:45 UTC, carbolymer commented on cardano-cli/cardano-cli.cabal
> +                      , cardano-api ^>= 8.1.0.1
`cardano-cli-test` , `cardano-cli-golden`, `depend on cardano-cli. The version bounds in `cardano-cli` should be enough to correctly resolve dependency version and the version bounds here seem redundant.

2023-05-15 06:46 UTC, carbolymer requested changes
Can we avoid specifying a version number in multiple places? That would be cumbersome in maintenance and requires mental overhead to remember that the change needs to be done in a few files.

2023-05-15 20:30 UTC, newhoggy commented
@carbolymer has created an ADR regarding constraints.  https://github.com/input-output-hk/cardano-node-wiki/pull/7

I think it's okay to merge this PR without resolving the questions in the ADR and come back to implement the ADR in a separate PR.

2023-05-15 20:44 UTC, erikd approved these changes

2023-05-16 07:29 UTC, carbolymer approved these changes

2023-05-16 15:34 UTC, mgmeier approved these changes

2023-05-17 00:07 UTC, JaredCorduan approved these changes

2023-05-17 08:33 UTC, olgahryniuk approved these changes

2023-05-18 04:57 UTC, merged