Update install.md
input-output-hk/cardano-node pull request #5174
Opened 2023-05-01 15:37 UTC by CarlosLopezDeLara

Installation instruction update. Use latest libsodium  from https://github.com/input-output-hk/iohk-nix/commit/ceb181d109a427e22184928221b85f313d1594ab

2023-05-01 15:41 UTC, disassembler approved these changes

2023-05-01 17:08 UTC, Jimbo4350 approved these changes
:+1:

2023-05-01 18:44 UTC, olgahryniuk approved these changes

2023-05-02 01:36 UTC, reqlez commented
I spent some time today trying to figure this out, only for somebody to link me this PR. I guess I was correct that the new sodium fork should be used from the new "audited" branch. By the way there is another commit on there after this one, that says "for backwards compatibility" but I'm guessing that's not needed?

However, my question is around this:
https://github.com/input-output-hk/cardano-node/commit/797289144ad87d494603f19b301e6dbf93310f81

The official documentation, states that it's "okay" to use the ported cbits with the " package cardano-crypto-praos   flags: -external-libsodium-vrf " option with the release version of libsodium ( libsodium/stable v1.0.18 ).

Is this still correct information, to be used in production? Or should this be removed as a recommendation as part of this install.md update?

2023-05-02 03:16 UTC, angerman commented
@CarlosLopezDeLara I'm not sure. It was updated in https://github.com/input-output-hk/iohk-nix/pull/522. We now have the situation where the cardano-node 8 release notes reference what was merged in https://github.com/input-output-hk/iohk-nix/pull/520, yet, iohk-nix we use in our nix builds, has https://github.com/input-output-hk/iohk-nix/pull/522.

The difference is effectively only https://github.com/input-output-hk/libsodium/commit/dbb48cce5429cb6585c9034f002568964f1ce567 commit. Are we certain we don't need the backwards compatibility anymore?

2023-05-02 03:18 UTC, angerman commented
@iquerejeta maybe you got some input here :-)

2023-05-02 19:58 UTC, CarlosLopezDeLara commented
As mentioned in [Discord](https://discord.com/channels/826816523368005654/915340581411106916/1103006156579942420) We're updating the docs to remove mentioning the external VRF hack. Here's the official position regarding using it in production:

In summary, it's not known to be wrong, rather it's not known to be ok, and since this is critical to security, the cautionary principle says don't use it in production.
The libsodium library has certain supported and documented ways to build and use the library. In particular it involves building the whole library using libsodiums own build system. Turning off the external-libsodium-vrf flag (and thus using the bundled C code instead) does neither of these things: it only builds little bits of libsodium and does not use the libsodium build system. So from the perspective of the libsodium developers it is not a supported configuration. For that reason it's not something we can currently recommend to use in production

2023-05-02 23:47 UTC, reqlez commented
What about secp ? Is recommendation to still use unreleased version?  https://github.com/bitcoin-core/secp256k1/releases/tag/v0.3.1  release versions now include schnorrsig by default it seems. In fact I built 8.0.0 with v0.3.1 minting blocks on preview right now with it.  Also seen on github devs are using it also?

2023-05-03 07:39 UTC, iquerejeta requested changes

2023-05-03 07:39 UTC, iquerejeta commented on doc/getting-started/install.md
> +git checkout a5baeccc
We should use the latest commit used in iohk-nix 

https://github.com/input-output-hk/iohk-nix/blob/master/overlays/crypto/libsodium.nix#L10

2023-05-03 19:50 UTC, CarlosLopezDeLara commented
closing in favor of https://github.com/input-output-hk/cardano-node/pull/5181

2023-05-03 19:50 UTC, closed without merging

2023-06-19 08:26 UTC, zhp1254 commented
> What about secp ? Is recommendation to still use unreleased version? https://github.com/bitcoin-core/secp256k1/releases/tag/v0.3.1 release versions now include schnorrsig by default it seems. In fact I built 8.0.0 with v0.3.1 minting blocks on preview right now with it. Also seen on github devs are using it also?

does cardano support secp256k1 transaction?

2023-06-19 09:42 UTC, iquerejeta commented
Hi @zhp1254 . Yes, secp256k1 transactions are supported. Here you can find an example https://github.com/input-output-hk/antaeus/blob/main/e2e-tests/test/Spec/Builtins/SECP256k1.hs