#5222 Remove `ApplicationName` and `ApplicationVersion` config parameters
input-output-hk/cardano-node pull request #5240
Opened 2023-05-12 14:57 UTC by carbolymer

# Description

This PR removes unnecessary configuration parametes from `cardano-node` config.
https://github.com/input-output-hk/cardano-node/issues/5222
see also: 

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated.  These may include:
  - golden tests
  - property tests
  - roundtrip tests
  - integration tests
  See [Runnings tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] Any changes are noted in the `CHANGELOG.md` for affected package
- [ ] The version bounds in `.cabal` files are updated
- [ ] CI passes. See note on CI.  The following CI checks are required:
  - [ ] Code is linted with `hlint`.  See `.github/workflows/check-hlint.yml` to get the `hlint` version
  - [ ] Code is formatted with `stylish-haskell`.  See `.github/workflows/stylish-haskell.yml` to get the `stylish-haskell` version
  - [ ] Code builds on Linux, MacOS and Windows for `ghc-8.10.7` and `ghc-9.2.7`
- [ ] Self-reviewed the diff

<! -- # Note on CI
If your PR is from a fork, the necessary CI jobs won't trigger automatically for security reasons.
You will need to get someone with write privileges.  Please contact IOG node developers to do this
for you.
-->

2023-05-26 09:57 UTC, carbolymer commented on .github/workflows/check-mainnet-config.yml
>        run: |
This now checks if all configuration fields from repo configuration are present in the nix configuration and are equal. Extra fields in nix configuration do not make this check fail.

2023-05-26 13:56 UTC, Jimbo4350 approved these changes

2023-05-26 13:56 UTC, Jimbo4350 requested changes
https://github.com/input-output-hk/cardano-node/pull/5240#discussion_r1206820184

2023-05-26 16:03 UTC, carbolymer commented on .github/workflows/check-mainnet-config.yml
>        run: |
We have a couple of python snippets in `cardano-node` already.
Anyway, I've rewritten this using `jq` - I hope it's better now.

2023-05-26 16:49 UTC, Jimbo4350 approved these changes

2023-05-26 19:13 UTC, CarlosLopezDeLara approved these changes
Nice!

2023-05-29 08:07 UTC, carbolymer commented
Hydra build failures are unrelated to this PR, they will be fixed by: https://github.com/input-output-hk/cardano-node/pull/5274/files

2023-06-01 23:17 UTC, angerman commented
What happens if those keys _are_ still in the config file? Does this produce a sensible error message, or simply ignore them?

2023-06-02 15:45 UTC, Jimbo4350 commented
> What happens if those keys _are_ still in the config file? Does this produce a sensible error message, or simply ignore them?

They are ignored. No need to produce an error message because they are legacy Byron parameters.

2023-06-02 18:09 UTC, disassembler approved these changes

2023-06-02 18:47 UTC, merged