Issue templates for cli, consensus, ledger and networking
input-output-hk/cardano-node pull request #5354
Opened 2023-06-21 14:24 UTC by carbolymer

# Description

Additional issue templates. 

https://github.com/carbolymer/cardano-node/issues/new/choose

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated.  These may include:
  - golden tests
  - property tests
  - roundtrip tests
  - integration tests
  See [Runnings tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] Any changes are noted in the `CHANGELOG.md` for affected package
- [ ] The version bounds in `.cabal` files are updated
- [ ] CI passes. See note on CI.  The following CI checks are required:
  - [ ] Code is linted with `hlint`.  See `.github/workflows/check-hlint.yml` to get the `hlint` version
  - [ ] Code is formatted with `stylish-haskell`.  See `.github/workflows/stylish-haskell.yml` to get the `stylish-haskell` version
  - [ ] Code builds on Linux, MacOS and Windows for `ghc-8.10.7` and `ghc-9.2.7`
- [ ] Self-reviewed the diff

# Note on CI
If your PR is from a fork, the necessary CI jobs won't trigger automatically for security reasons.
You will need to get someone with write privileges.  Please contact IOG node developers to do this
for you.

2023-07-28 12:35 UTC, Jimbo4350 requested changes
So we moved the cli and api to avoid precisely this situation, a mix of issues that pertained to other components.

2023-07-28 12:35 UTC, Jimbo4350 commented on .github/ISSUE_TEMPLATE/component-cardano-cli.md
> +labels: ["type: bug", "comp: cardano-cli"]
We moved the cli and api out of cardano-node to avoid non-node related issues from being raised in cardano-node.

2023-07-28 12:35 UTC, Jimbo4350 commented on .github/ISSUE_TEMPLATE/component-consensus.md
> +name: Bug report related to consensus
When a user tries to create a consensus related issue, why not just have a link to the consensus repo?

2023-12-10 00:16 UTC, newhoggy commented
This PR looks obsolete.

Re-open if not.

2023-12-10 00:16 UTC, closed without merging